# Pins the exposure pipeline as it behaves TODAY, defects included.
#
# Every expectation in this file was OBTAINED BY RUNNING the exported entry
# points, never derived from the codebook, the ladder source or any
# re-implementation. Several pinned values are known defects. They are frozen
# on purpose: when a repair lands, the diff of this file is the record of what
# changed. Do not "correct" an expectation here.
#
# THE CORE OF THE PIN IS THE TWO FROZEN LITERAL TABLES BELOW. An expectation
# read out of the same function body the test then executes moves with the
# implementation and proves nothing: relabel a rung and the oracle relabels
# itself. So the expected category always comes from a literal, generated once
# by running the classifier and pasted in.
#
# The file is organised by pipeline stage:
#   input filter -> normaliser -> ladder -> materialisation ->
#   rule evaluation -> approach resolution -> downstream projection/contract.

# ---------------------------------------------------------------- harness ----

# `ladder_rungs()` parses the ladder out of the PARSED FUNCTION BODY (never the
# file on disk, which is absent from an installed package).
#
# IT SUPPLIES COVERAGE BOOKKEEPING ONLY, AND MUST NEVER SUPPLY AN EXPECTED
# VALUE. Reading the expected category out of the same function body the test
# then executes makes the comparison vacuous: relabel a rung and the oracle
# moves with the implementation. The expected side always comes from the frozen
# literal tables below.
ladder_rungs <- function(fn) {
  find_fcase <- function(e) {
    if (!is.call(e)) {
      return(NULL)
    }
    h <- e[[1]]
    if (identical(h, quote(fcase)) || identical(h, quote(data.table::fcase))) {
      return(e)
    }
    parts <- as.list(e)
    for (i in seq_along(parts)) {
      # `x[, j]` puts an empty symbol in the call; skip it without binding it
      if (identical(parts[i], list(quote(expr = )))) {
        next
      }
      hit <- find_fcase(parts[[i]])
      if (!is.null(hit)) {
        return(hit)
      }
    }
    NULL
  }
  fc <- find_fcase(body(utils::removeSource(fn)))
  stopifnot(!is.null(fc))
  a <- as.list(fc)[-1]
  stopifnot(length(a) %% 2 == 0)
  data.table::data.table(
    pattern = vapply(a[seq(1, length(a), 2)], function(z) as.character(z[[3]]), ""),
    declared = vapply(a[seq(2, length(a), 2)], as.character, "")
  )
}

# ------------------------------------------------------- frozen expectations ----

# THE PIN ITSELF. Both tables were generated by RUNNING the classifier over the
# strings that name them, and pasted in as literals. Neither is derived from
# the function body, from `ladder_rungs()`, or from the codebook.
#
# They are NOT a clinically approved product-to-category map. They record what
# the classifier returns TODAY, defects included. When a repair lands, the diff
# of these two tables is the record of what changed.
#
# Both ladders were verified to return identical values for every entry, so one
# table serves both.

# The category each rung DECLARES, in ladder order, with duplicates. Names are
# the patterns, values the declared categories; a name repeats where a pattern
# has more than one rung.
#
# Generated by running `ladder_rungs()` once and pasting the result in. That is
# the SAME direction of information flow as the tables above: the frozen
# literal is the expected side, and the parse supplies only the observed side.
#
# This table exists because the observed tables cannot see a SHADOWED rung. The
# `Presomen -> B10` rung never fires, so relabelling it to B12 changes nothing
# observable and every other test stays green. It bites later: the shadowed
# rungs are exactly what a future reordering repair unshadows, and if the dead
# label drifted in the meantime the repair lands the wrong category silently.
#
# The sequence identity also pins LENGTH and PER-PATTERN MULTIPLICITY, so a
# second, shadowed rung for an existing pattern cannot be added unnoticed.
FROZEN_RUNG_DECLARED <- c(
  "Oestring" = "A3",
  "Vagidonna" = "A3",
  "Vagifem" = "A3",
  "Vagirux" = "A3",
  "EstradiolSUN" = "A3",
  "Menovag" = "A3",
  "Blissel" = "A4",
  "Estrokad" = "A4",
  "Ovesterin" = "A4",
  "Gelistrol" = "A4",
  "Divigel" = "A1",
  "Estradot" = "A1",
  "Estrogel" = "A1",
  "Lenzetto" = "A1",
  "Dermestril" = "A1",
  "Evorel" = "A1",
  "Oesclim" = "A1",
  "Climara" = "A1",
  "Evopad" = "A1",
  "Femseven" = "A1",
  "Progynon" = "A2",
  "Femanest" = "A2",
  "Oestriolaspen" = "A5",
  "Premarina" = "A6",
  "Presomen" = "A6",
  "Delestrogen" = "A7",
  "Neofollin" = "A7",
  "Estalis" = "B1",
  "EstalisSekvens" = "B1",
  "Activelle" = "B2",
  "Cliovelle" = "B2",
  "Eviana" = "B2",
  "Femanor" = "B2",
  "Noresmea" = "B2",
  "Kliogest" = "B2",
  "Indivina" = "B3",
  "Duova" = "B3",
  "Premelle" = "B3",
  "Premellesekvens" = "B3",
  "Femostonconti" = "B4",
  "Climodien" = "B5",
  "Angemin" = "B6",
  "Sequidot" = "B7",
  "Femasekvens" = "B8",
  "Trisekvens" = "B8",
  "Novofem" = "B8",
  "DivinaPlus" = "B9",
  "Trivina" = "B9",
  "Presomen" = "B10",
  "Femoston" = "B11",
  "Cyclabil" = "B11",
  "Crinone" = "C1",
  "Cyclogest" = "C1",
  "Lugesteron" = "C1",
  "Lutinus" = "C1",
  "Utrogest" = "C1",
  "Utrogestan" = "C1",
  "Progesteron" = "C1",
  "Extemporeprogesteron" = "C1",
  "ProgesteronMICAPL" = "C1",
  "Prolutex" = "C1",
  "Visanne" = "C3",
  "Desogestrel" = "C3",
  "Cerazette" = "C3",
  "Azalia" = "C3",
  "Gestrina" = "C3",
  "Velavel" = "C3",
  "Vinelle" = "C3",
  "Zarelle" = "C3",
  "Slinda" = "C3",
  "PrimolutNor" = "C4",
  "Provera" = "C4",
  "Duphaston" = "C4",
  "Orgametril" = "C4",
  "Gestapuran" = "C4",
  "Duphaston" = "C5",
  "DepoProvera" = "D1",
  "Nexplanon" = "D2",
  "Implanon" = "D2",
  "Folistrel" = "D2",
  "Jadelle" = "D3",
  "Jaydess" = "E1",
  "Kyleena" = "E1",
  "Levosert" = "E1",
  "Levosertone" = "E1",
  "Mirena" = "E1",
  "Livial" = "F1",
  "Tibelia" = "F1",
  "Tibocina" = "F1",
  "TibolonAristo" = "F1",
  "TibolonMylan" = "F1",
  "TibolonOrifarm" = "F1",
  "Boltin" = "F1",
  "Duavive" = "G1",
  "Nebido" = "H1",
  "Testogel" = "H1",
  "Undestor" = "H1",
  "Undestortestocaps" = "H1",
  "Testovirondepot" = "H1",
  "Intrinsa" = "H1",
  "Testavan" = "H1",
  "Testim" = "H1",
  "Testovirondepot" = "H1",
  "Tostran" = "H1",
  "Tostrex" = "H1",
  "MiniPe" = "I1",
  "Exlutena" = "I2"
)

# Every distinct pattern literal in the ladder, and the category the classifier
# actually returns for it. Where that differs from the category the rung
# declares, the rung is shadowed by an earlier one: `Presomen` -> A6 not B10,
# `Duphaston` -> C4 not C5, `DepoProvera` -> C4 not D1.
FROZEN_PATTERN_CATEGORY <- c(
  "Oestring" = "A3",
  "Vagidonna" = "A3",
  "Vagifem" = "A3",
  "Vagirux" = "A3",
  "EstradiolSUN" = "A3",
  "Menovag" = "A3",
  "Blissel" = "A4",
  "Estrokad" = "A4",
  "Ovesterin" = "A4",
  "Gelistrol" = "A4",
  "Divigel" = "A1",
  "Estradot" = "A1",
  "Estrogel" = "A1",
  "Lenzetto" = "A1",
  "Dermestril" = "A1",
  "Evorel" = "A1",
  "Oesclim" = "A1",
  "Climara" = "A1",
  "Evopad" = "A1",
  "Femseven" = "A1",
  "Progynon" = "A2",
  "Femanest" = "A2",
  "Oestriolaspen" = "A5",
  "Premarina" = "A6",
  "Presomen" = "A6",
  "Delestrogen" = "A7",
  "Neofollin" = "A7",
  "Estalis" = "B1",
  "EstalisSekvens" = "B1",
  "Activelle" = "B2",
  "Cliovelle" = "B2",
  "Eviana" = "B2",
  "Femanor" = "B2",
  "Noresmea" = "B2",
  "Kliogest" = "B2",
  "Indivina" = "B3",
  "Duova" = "B3",
  "Premelle" = "B3",
  "Premellesekvens" = "B3",
  "Femostonconti" = "B4",
  "Climodien" = "B5",
  "Angemin" = "B6",
  "Sequidot" = "B7",
  "Femasekvens" = "B8",
  "Trisekvens" = "B8",
  "Novofem" = "B8",
  "DivinaPlus" = "B9",
  "Trivina" = "B9",
  "Femoston" = "B11",
  "Cyclabil" = "B11",
  "Crinone" = "C1",
  "Cyclogest" = "C1",
  "Lugesteron" = "C1",
  "Lutinus" = "C1",
  "Utrogest" = "C1",
  "Utrogestan" = "C1",
  "Progesteron" = "C1",
  "Extemporeprogesteron" = "C1",
  "ProgesteronMICAPL" = "C1",
  "Prolutex" = "C1",
  "Visanne" = "C3",
  "Desogestrel" = "C3",
  "Cerazette" = "C3",
  "Azalia" = "C3",
  "Gestrina" = "C3",
  "Velavel" = "C3",
  "Vinelle" = "C3",
  "Zarelle" = "C3",
  "Slinda" = "C3",
  "PrimolutNor" = "C4",
  "Provera" = "C4",
  "Duphaston" = "C4",
  "Orgametril" = "C4",
  "Gestapuran" = "C4",
  "DepoProvera" = "C4",
  "Nexplanon" = "D2",
  "Implanon" = "D2",
  "Folistrel" = "D2",
  "Jadelle" = "D3",
  "Jaydess" = "E1",
  "Kyleena" = "E1",
  "Levosert" = "E1",
  "Levosertone" = "E1",
  "Mirena" = "E1",
  "Livial" = "F1",
  "Tibelia" = "F1",
  "Tibocina" = "F1",
  "TibolonAristo" = "F1",
  "TibolonMylan" = "F1",
  "TibolonOrifarm" = "F1",
  "Boltin" = "F1",
  "Duavive" = "G1",
  "Nebido" = "H1",
  "Testogel" = "H1",
  "Undestor" = "H1",
  "Undestortestocaps" = "H1",
  "Testovirondepot" = "H1",
  "Intrinsa" = "H1",
  "Testavan" = "H1",
  "Testim" = "H1",
  "Tostran" = "H1",
  "Tostrex" = "H1",
  "MiniPe" = "I1",
  "Exlutena" = "I2"
)

# Every product name in the codebook's `MHT_groups` sheet, and the category the
# classifier actually returns for it.
FROZEN_PRODUCT_CATEGORY <- c(
  "Divigel" = "A1",
  "Estradot" = "A1",
  "Estrogel" = "A1",
  "Lenzetto" = "A1",
  "Dermestril" = "A1",
  "Evorel" = "A1",
  "Oesclim" = "A1",
  "Climara" = "A1",
  "Evopad" = "A1",
  "Femseven" = "A1",
  "Progynon" = "A2",
  "Femanest" = "A2",
  "Oestring" = "A3",
  "Vagidonna" = "A3",
  "Vagifem" = "A3",
  "Vagirux" = "A3",
  "Estradiol SUN" = "A3",
  "Menovag" = "A3",
  "Blissel" = "A4",
  "Estrokad" = "A4",
  "Ovesterin" = "A4",
  "Gelistrol" = "A4",
  "Oestriol aspen" = "A5",
  "Premarina" = "A6",
  "Presomen" = "A6",
  "Delestrogen" = "A7",
  "Neofollin" = "A7",
  "Estalis" = "B1",
  "Estalis Sekvens" = "B1",
  "Activelle" = "B2",
  "Cliovelle" = "B2",
  "Eviana" = "B2",
  "Femanor" = "B2",
  "Noresmea" = "B2",
  "Kliogest" = "B2",
  "Indivina" = "B3",
  "Duova" = "B3",
  "Premelle" = "B3",
  "Premelle sekvens" = "B3",
  "Femostonconti" = "B4",
  "Lafamme" = NA_character_,
  "Climodien" = "B5",
  "Angemin" = "B6",
  "Sequidot" = "B7",
  "Femasekvens" = "B8",
  "Trisekvens" = "B8",
  "Novofem" = "B8",
  "Divina Plus" = "B9",
  "Trivina" = "B9",
  "Femoston" = "B11",
  "Cyclabil" = "B11",
  "Crinone" = "C1",
  "Cyclogest" = "C1",
  "Lugesteron" = "C1",
  "Lutinus" = "C1",
  "Utrogest" = "C1",
  "Utrogestan" = "C1",
  "Extrempore progesteron" = NA_character_,
  "Progesteron MIC APL" = "C1",
  "Prolutex" = "C1",
  "Visanne" = "C3",
  "Endovelle" = NA_character_,
  "Desogestrel" = "C3",
  "Cerazette" = "C3",
  "Azalia" = "C3",
  "Gestrina" = "C3",
  "Velavel" = "C3",
  "Vinelle" = "C3",
  "Zarelle" = "C3",
  "Slinda" = "C3",
  "Primolut-Nor" = NA_character_,
  "Provera" = "C4",
  "Orgametril" = "C4",
  "Gestapuran" = "C4",
  "Duphaston" = "C4",
  "Depo-Provera" = "C4",
  "Nexplanon" = "D2",
  "Implanon" = "D2",
  "Folistrel" = "D2",
  "Jadelle" = "D3",
  "Jaydess" = "E1",
  "Kyleena" = "E1",
  "Levosert" = "E1",
  "Levosertone" = "E1",
  "Mirena" = "E1",
  "Livial" = "F1",
  "Tibelia" = "F1",
  "Tibocina" = "F1",
  "Tibolon Aristo" = "F1",
  "Tibolon Mylan" = "F1",
  "Tibolon Orifarm" = "F1",
  "Boltin" = "F1",
  "Duavive" = "G1",
  "Nebido" = "H1",
  "Testogel" = "H1",
  "Undestor" = "H1",
  "Undestortestocaps" = "H1",
  "Testosteron depot" = NA_character_,
  "Intrinsa" = "H1",
  "Testavan" = "H1",
  "Testim" = "H1",
  "Testoviron depot" = "H1",
  "Tostran" = "H1",
  "Tostrex" = "H1",
  "Mini-Pe" = NA_character_,
  "Exlutena" = "I2"
)

ladders <- list(
  v20230509 = mht:::lmed_categorize_product_names_v20230509,
  v20250909 = mht:::lmed_categorize_product_names_v20250909
)

classify <- function(fn, produkt) {
  x <- data.table::data.table(produkt = produkt)
  fn(x)
  x$product_category
}

normalise <- function(fn, produkt) {
  x <- data.table::data.table(produkt = produkt)
  fn(x)
  x$produkt_clean
}

# The authoritative product universe: sheet `MHT_groups`, column `Preparatnamn`
# of the codebook both entry points read.
workbook_products <- function() {
  wb <- suppressMessages(suppressWarnings(readxl::read_excel(
    system.file("2023-mht", "dataDictionary20241105.xlsx", package = "mht"),
    sheet = "MHT_groups"
  )))
  data.table::setDT(wb)
  unique(stats::na.omit(wb$Preparatnamn))
}

weeks_between <- function(from, to) {
  unique(cstime::date_to_isoyearweek_c(
    seq(as.Date(from), as.Date(to), by = "week")
  ))
}

# Drive the real 2026 entry point and hand back the mutated skeleton.
run_2026 <- function(lmed, ids, weeks) {
  skeleton <- data.table::CJ(id = ids, isoyearweek = weeks, sorted = TRUE)
  suppressWarnings(add_lmed_v20250909(skeleton, lmed, verbose = FALSE))
  skeleton
}

# Drive the real 2023 entry point and hand back the mutated skeleton.
run_2023 <- function(lmed, ids, weeks) {
  skeleton <- data.table::CJ(id = ids, isoyearweek = weeks, sorted = TRUE)
  suppressMessages(suppressWarnings(add_lmed_v20230509(skeleton, lmed)))
  skeleton
}

# The only observable of the dispensed duration through an exported entry
# point: the ISO weeks in which the product's category column is TRUE.
#
# THE ANCHOR DATE IS LEAD, NOT PACKAGING, AND ONE ANCHOR IS DIRECTIONAL.
#
# Every duration this file pins is a multiple of 7 (1680, 1008, and n * 28 from
# the minimum-dose loop), so the interval's end lands on the same weekday as
# the anchor. That weekday decides which one-day change is visible, and each
# anchor sees exactly ONE direction. Measured, not reasoned:
#
#            anchor 2016-01-03 (Sun)      anchor 2016-01-04 (Mon)
#   1679          last = 2020-32               last = 2020-32
#   1680          last = 2020-32               last = 2020-33
#   1681          last = 2020-33               last = 2020-33
#
# So the Sunday anchor detects LONGER by one day and is BLIND to shorter; the
# Monday anchor is the mirror image. Two anchors together give one-day
# sensitivity in both directions, and
# "the duration pins detect a one-day change in BOTH directions" runs both.
#
# The default below is the Sunday anchor, so every pin in this file that does
# not name an anchor detects a lengthening and not a shortening.
#
# Two earlier versions of this comment were wrong: the first claimed weekly
# granularity was an inherent limit of the exported surface, the second claimed
# the Sunday anchor gave general one-day sensitivity. Both were written without
# running the shorter case. It is run now, above.
span_2026 <- function(produkt, fddd, category, weeks, anchor = "2016-01-03") {
  skeleton <- run_2026(
    data.table::data.table(
      lopnr = 1L,
      produkt = produkt,
      edatum = as.Date(anchor),
      fddd = fddd
    ),
    ids = 1L,
    weeks = weeks
  )
  w <- skeleton[get(category) == TRUE]$isoyearweek
  list(first = w[1], last = w[length(w)], n = length(w))
}

# ------------------------------------------------------------ input filter ----

test_that("a prescription whose id is absent from the skeleton reaches nothing", {
  weeks <- weeks_between("2015-01-05", "2016-12-26")
  skeleton <- run_2026(
    data.table::data.table(
      lopnr = c(1L, 99L),
      produkt = "Divigel",
      edatum = as.Date("2015-02-02"),
      fddd = 90
    ),
    ids = 1:2,
    weeks = weeks
  )
  expect_identical(sort(unique(skeleton[A1 == TRUE]$id)), 1L)
})

test_that("a negative or missing fddd drops the row and warns", {
  weeks <- weeks_between("2015-01-05", "2016-12-26")
  for (bad in list(-10, NA_real_)) {
    skeleton <- data.table::CJ(id = 1L, isoyearweek = weeks, sorted = TRUE)
    expect_warning(
      add_lmed_v20250909(
        skeleton,
        data.table::data.table(
          lopnr = 1L,
          produkt = "Divigel",
          edatum = as.Date("2015-02-02"),
          fddd = bad
        ),
        verbose = FALSE
      ),
      "dropped"
    )
    expect_false(any(skeleton$A1))
  }
})

test_that("the caller's lmed keeps its values but gains an index attribute", {
  # The documentation says `lmed` is NOT modified. Its VALUES are not, but the
  # subsetting in the entry point attaches a secondary-index cache to the
  # caller's own object by reference.
  weeks <- weeks_between("2015-01-05", "2016-12-26")
  lmed <- data.table::data.table(
    lopnr = c(1L, 99L),
    produkt = "Divigel",
    edatum = as.Date("2015-02-02"),
    fddd = 90
  )
  before <- data.table::copy(lmed)
  run_2026(lmed, ids = 1:2, weeks = weeks)

  expect_identical(as.data.frame(lmed), as.data.frame(before))
  expect_identical(names(lmed), names(before))
  expect_false("index" %in% names(attributes(before)))
  expect_true("index" %in% names(attributes(lmed)))
})

# -------------------------------------------------------------- normaliser ----

test_that("the normaliser strips spaces and keeps hyphens, in both ladders", {
  # `produkt_clean` is assigned twice; the hyphen-stripping assignment is
  # immediately overwritten by the space-stripping one, so only spaces survive.
  for (nm in names(ladders)) {
    expect_identical(
      normalise(ladders[[nm]], c("Femoston conti", "Femoston-conti", "Mini-Pe")),
      c("Femostonconti", "Femoston-conti", "Mini-Pe"),
      info = nm
    )
  }
})

# ---------------------------------------------------------- ladder / rungs ----

test_that("every ladder pattern classifies to its frozen category, both ladders", {
  # THE PIN. Expected side is the frozen literal, obtained by execution and
  # pasted in. Relabelling ANY rung — `Tibelia` from F1 to B2, say — turns this
  # red, because the expectation does not move with the implementation.
  for (nm in names(ladders)) {
    expect_identical(
      classify(ladders[[nm]], names(FROZEN_PATTERN_CATEGORY)),
      unname(FROZEN_PATTERN_CATEGORY),
      info = nm
    )
  }
})

test_that("every codebook product classifies to its frozen category, both ladders", {
  # THE PIN, over the register-facing spellings rather than the rung literals.
  # Order-insensitive: the codebook's row order is not contractual, so the
  # lookup is by name.
  prods <- workbook_products()
  shared <- intersect(prods, names(FROZEN_PRODUCT_CATEGORY))
  for (nm in names(ladders)) {
    expect_identical(
      classify(ladders[[nm]], shared),
      unname(FROZEN_PRODUCT_CATEGORY[shared]),
      info = nm
    )
  }
})

test_that("the rung sequence matches the frozen declared table, both ladders", {
  # Pins the DECLARED label of every rung, including the three that can never
  # fire, plus the order and the per-pattern multiplicity of the whole ladder.
  #
  # `ladder_rungs()` supplies the OBSERVED-FROM-SOURCE side only. The expected
  # side is the frozen literal, so this is not the vacuous comparison that was
  # removed: relabel a rung and the literal does not move with it.
  for (nm in names(ladders)) {
    r <- ladder_rungs(ladders[[nm]])
    # order and multiplicity
    expect_identical(r$pattern, names(FROZEN_RUNG_DECLARED), info = nm)
    # the declared label of every rung, shadowed ones included
    expect_identical(r$declared, unname(FROZEN_RUNG_DECLARED), info = nm)
  }

  # named separately so a duplicate-rung failure reads as one
  counts <- table(names(FROZEN_RUNG_DECLARED))
  expect_identical(
    sort(names(counts)[counts > 1L]),
    c("Duphaston", "Presomen", "Testovirondepot")
  )
  expect_length(FROZEN_RUNG_DECLARED, 107L)
})

test_that("the frozen tables cover every rung and every codebook product", {
  # COVERAGE BOOKKEEPING. `ladder_rungs()` is used here and in the block above,
  # nowhere else, and it supplies observed-from-source values only.
  #
  # This block and the one above ARE deliberately contractual: they are the only
  # places in the file that fail on an addition or a relabel rather than on a
  # change in observable behaviour. That is the intent, for two reasons.
  #
  # First, a new rung or a new codebook product that nobody pinned is exactly
  # the gap a pinning suite exists to report.
  #
  # Second, a SHADOWED rung has no observable behaviour to change, so freezing
  # its declared label is the only way to notice it drifting before the repair
  # that unshadows it lands.
  #
  # The repair in both cases is one generated line in a frozen table.
  for (nm in names(ladders)) {
    patterns <- ladder_rungs(ladders[[nm]])$pattern
    expect_setequal(unique(patterns), names(FROZEN_PATTERN_CATEGORY))
    # a rung present in source but in neither frozen table cannot hide
    expect_setequal(unique(patterns), unique(names(FROZEN_RUNG_DECLARED)))
  }
  expect_setequal(workbook_products(), names(FROZEN_PRODUCT_CATEGORY))
})

test_that("PINNED DEFECT: the B10, C5 and D1 rungs can never fire", {
  # Asserted directly against the classifier, independent of both the parsing
  # helper and the frozen tables.
  #
  # "Never" is exact here, and this is the argument. A rung fires only for a
  # string containing its own pattern. Each of these three patterns classifies
  # as something else, which means an EARLIER pattern is a substring of it. Any
  # string containing the later pattern therefore also contains the earlier
  # one, and reaches the earlier rung first. So no input at all can reach these
  # three, and the declared categories B10, C5 and D1 are unreachable.
  for (nm in names(ladders)) {
    expect_identical(
      classify(ladders[[nm]], c("Presomen", "Duphaston", "DepoProvera")),
      c("A6", "C4", "C4"),
      info = nm
    )
    # a longer register-style spelling reaches the same shadowing rung
    expect_identical(
      classify(ladders[[nm]], c("Presomen 0,3 mg", "Duphaston 10 mg", "DepoProvera 150 mg")),
      c("A6", "C4", "C4"),
      info = nm
    )
  }
  expect_false(any(FROZEN_PATTERN_CATEGORY %in% c("B10", "C5", "D1")))
})

test_that("the codebook product universe reaches 27 categories and misses 6", {
  # Set-based, so a reordered or extended codebook does not cry wolf: only a
  # change in WHICH categories are reachable, or WHICH names miss, fails here.
  for (nm in names(ladders)) {
    got <- classify(ladders[[nm]], workbook_products())
    expect_setequal(
      unique(stats::na.omit(got)),
      c(
        "A1", "A2", "A3", "A4", "A5", "A6", "A7",
        "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "B11",
        "C1", "C3", "C4", "D2", "D3", "E1", "F1", "G1", "H1", "I2"
      )
    )
    expect_setequal(
      workbook_products()[is.na(got)],
      c(
        "Lafamme",
        "Extrempore progesteron",
        "Endovelle",
        "Primolut-Nor",
        "Testosteron depot",
        "Mini-Pe"
      )
    )
  }
})

# ---------------------------------------------------------- materialisation ----

test_that("both entry points create the same 33 category columns, and G1 is not one", {
  weeks <- weeks_between("2015-01-05", "2016-03-28")
  lmed_2026 <- data.table::data.table(
    lopnr = 1L, produkt = "Divigel", edatum = as.Date("2015-02-02"), fddd = 90
  )
  lmed_2023 <- data.table::data.table(
    p1163_lopnr_personnr = 1L, produkt = "Divigel",
    edatum = as.Date("2015-02-02"), fddd = 90
  )
  expected <- c(
    "A1", "A2", "A3", "A4", "A5", "A6", "A7",
    "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "B10", "B11", "B12",
    "C1", "C2", "C3", "C4", "C5",
    "D1", "D2", "D3", "D4",
    "E1", "F1", "H1", "I1", "I2"
  )
  for (skeleton in list(
    run_2026(lmed_2026, ids = 1L, weeks = weeks),
    run_2023(lmed_2023, ids = 1L, weeks = weeks)
  )) {
    # set-based: WHICH columns exist is the pinned property, not their order
    expect_setequal(intersect(names(skeleton), c(expected, "G1")), expected)
    expect_false("G1" %in% names(skeleton))
  }
})

test_that("PINNED DEFECT: seven category columns stay FALSE over the codebook", {
  # SCOPE: false over the CODEBOOK PRODUCT UNIVERSE, which is what this test
  # drives. It is NOT a claim that no input at all can reach them, and three of
  # the seven are reachable by other spellings:
  #   I1  -- `MiniPe` and `Mini Pe` both classify I1; only the codebook's own
  #          spelling `Mini-Pe` misses, because the hyphen survives.
  #   B10, C5, D1 -- genuinely unreachable, proved separately in
  #          "PINNED DEFECT: the B10, C5 and D1 rungs can never fire".
  #   B12, C2, D4 -- declared as columns with no ladder rung at all.
  # The counter-fact for I1 is asserted below so the scoping cannot drift.
  #
  # Driven over the whole authoritative product universe, one product per
  # person, so nothing but the pipeline decides which columns light up.
  prods <- workbook_products()
  weeks <- weeks_between("2015-01-05", "2016-03-28")
  lmed <- data.table::data.table(
    lopnr = seq_along(prods),
    produkt = prods,
    edatum = as.Date("2015-02-02"),
    fddd = 365
  )
  skeleton <- run_2026(lmed, ids = seq_along(prods), weeks = weeks)
  cats <- setdiff(names(skeleton), c(
    "id", "isoyearweek", "approach1", "approach2", "approach3",
    grep("^rd_approach", names(skeleton), value = TRUE)
  ))
  lit <- vapply(cats, function(k) any(skeleton[[k]]), logical(1))
  expect_setequal(
    names(lit)[!lit],
    c("B10", "B12", "C2", "C5", "D1", "D4", "I1")
  )
  expect_setequal(
    names(lit)[lit],
    c(
      "A1", "A2", "A3", "A4", "A5", "A6", "A7",
      "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "B11",
      "C1", "C3", "C4", "D2", "D3", "E1", "F1", "H1", "I2"
    )
  )

  # I1 is FALSE only because of the codebook spelling, not because the rung is
  # unreachable. This is the counter-fact that scopes the claim above.
  for (nm in names(ladders)) {
    expect_identical(
      classify(ladders[[nm]], c("MiniPe", "Mini Pe", "Mini-Pe")),
      c("I1", "I1", NA_character_),
      info = nm
    )
  }
})

test_that("PINNED DEFECT: a G1 product is classified and then reaches no column", {
  weeks <- weeks_between("2015-01-05", "2016-03-28")
  for (nm in names(ladders)) {
    expect_identical(classify(ladders[[nm]], "Duavive"), "G1", info = nm)
  }
  skeleton <- run_2026(
    data.table::data.table(
      lopnr = 1L, produkt = "Duavive", edatum = as.Date("2015-02-02"), fddd = 365
    ),
    ids = 1L,
    weeks = weeks
  )
  expect_false("G1" %in% names(skeleton))
  cats <- setdiff(names(skeleton), c(
    "id", "isoyearweek", "approach1", "approach2", "approach3",
    grep("^rd_approach", names(skeleton), value = TRUE)
  ))
  expect_false(any(vapply(cats, function(k) any(skeleton[[k]]), logical(1))))
})

# --------------------------------------------------------- rule evaluation ----

test_that("a product matching one workbook row applies that row once", {
  weeks <- weeks_between("2015-12-27", "2020-12-27")
  # `Utrogest 100mg` matches the `Utrogest` row only (8 mg/month, min 3 months):
  # floor(30/8) = 3 months -> 3 * 28 = 84 days.
  expect_identical(
    span_2026("Utrogest 100mg", 30, "C1", weeks),
    span_2026("Divigel", 84, "A1", weeks)
  )
  expect_identical(
    span_2026("Utrogest 100mg", 30, "C1", weeks),
    list(first = "2015-53", last = "2016-12", n = 13L)
  )
})

test_that("PINNED DEFECT: two matching workbook rows compound the minimum-dose rule", {
  # `Utrogest` is a prefix of `Utrogestan`, so `Utrogestan 100mg Capsules`
  # matches BOTH workbook rows. The loop writes `fddd :=` once per matching
  # row and each iteration reads the previous result, so from fddd = 30 the
  # duration compounds 30 -> 84 -> 196. Applied singly it would be 84 or 56.
  weeks <- weeks_between("2015-12-27", "2020-12-27")
  observed <- span_2026("Utrogestan 100mg Capsules", 30, "C1", weeks)
  expect_identical(observed, span_2026("Divigel", 196, "A1", weeks))
  expect_identical(observed, list(first = "2015-53", last = "2016-28", n = 29L))
  expect_false(identical(observed, span_2026("Divigel", 84, "A1", weeks)))
  expect_false(identical(observed, span_2026("Divigel", 56, "A1", weeks)))
})

test_that("PINNED DEFECT: the minimum-dose loop matches the RAW product name", {
  # The ladder matches the NORMALISED name; the minimum-dose loop matches the
  # RAW one. The two stages disagree about what a product name is.
  #
  # `Progesteron MIC APL` is the witness, and it is a real codebook product.
  # Its raw and normalised forms differ (spaces are stripped), and it reaches
  # the loop: the ladder classifies it C1 on `ProgesteronMICAPL`, then the loop
  # matches the RAW name against the `Progesteron MIC APL` codebook row
  # (3.33 mg/month, min 3 months): floor(10/3.33) = 3 -> 3 * 28 = 84 days.
  #
  # Point the loop at `produkt_clean` and the row stops matching, because
  # `ProgesteronMICAPL` does not contain `Progesteron MIC APL`: the dispensed
  # 10 days survive untouched and the span collapses from 13 weeks to 3.
  weeks <- weeks_between("2015-12-27", "2020-12-27")

  for (nm in names(ladders)) {
    expect_identical(classify(ladders[[nm]], "Progesteron MIC APL"), "C1", info = nm)
    expect_identical(
      normalise(ladders[[nm]], "Progesteron MIC APL"),
      "ProgesteronMICAPL",
      info = nm
    )
  }

  observed <- span_2026("Progesteron MIC APL", 10, "C1", weeks)
  expect_identical(observed, span_2026("Divigel", 84, "A1", weeks))
  expect_identical(observed, list(first = "2015-53", last = "2016-12", n = 13L))
  # the whole point: the loop DID fire, so the dispensed 10 days did not survive
  expect_false(identical(observed, span_2026("Divigel", 10, "A1", weeks)))
})

# ---------------------------------------------------- duration precedence ----

test_that("the IUD rule overrides the dispensed fddd", {
  weeks <- weeks_between("2015-12-27", "2050-12-25")
  reference <- span_2026("Divigel", 1680, "A1", weeks)
  expect_identical(span_2026("Mirena", 1, "E1", weeks), reference)
  expect_identical(span_2026("Jadelle", 1, "D3", weeks), reference)
  expect_identical(reference, list(first = "2015-53", last = "2020-32", n = 241L))
  # one day LONGER lands in the next ISO week under the default Sunday anchor.
  # One day SHORTER does not, and is covered by the two-anchor test below.
  expect_false(identical(reference, span_2026("Divigel", 1681, "A1", weeks)))
})

test_that("the duration pins detect a one-day change in BOTH directions", {
  # ONE ANCHOR IS NOT ENOUGH, and saying otherwise was the previous defect in
  # this file. Every pinned duration is a multiple of 7, so the interval ends on
  # the anchor's own weekday, and that decides which direction is visible:
  #
  #   Sunday anchor  -- 1680 and 1679 share an ISO week; 1681 does not. +1 only.
  #   Monday anchor  -- 1680 and 1681 share an ISO week; 1679 does not. -1 only.
  #
  # Running both is what makes the duration pins sensitive to a single day in
  # either direction. Values below were measured, not derived.
  weeks <- weeks_between("2015-12-27", "2050-12-25")
  sun <- "2016-01-03"
  mon <- "2016-01-04"

  # ---- lengthening: seen from the Sunday anchor, invisible from Monday
  iud_sun <- span_2026("Mirena", 1, "E1", weeks, sun)
  expect_identical(iud_sun, span_2026("Divigel", 1680, "A1", weeks, sun))
  expect_false(identical(iud_sun, span_2026("Divigel", 1681, "A1", weeks, sun)))
  # the blind direction, pinned as blind so nobody later reads it as covered
  expect_identical(iud_sun, span_2026("Divigel", 1679, "A1", weeks, sun))

  # ---- shortening: seen from the Monday anchor, invisible from Sunday
  iud_mon <- span_2026("Mirena", 1, "E1", weeks, mon)
  expect_identical(iud_mon, span_2026("Divigel", 1680, "A1", weeks, mon))
  expect_false(identical(iud_mon, span_2026("Divigel", 1679, "A1", weeks, mon)))
  expect_identical(iud_mon, span_2026("Divigel", 1681, "A1", weeks, mon))

  # the Jaydess duration behaves the same way, in both directions
  jay_sun <- span_2026("Jaydess", 1, "E1", weeks, sun)
  expect_false(identical(jay_sun, span_2026("Divigel", 1009, "A1", weeks, sun)))
  jay_mon <- span_2026("Jaydess", 1, "E1", weeks, mon)
  expect_false(identical(jay_mon, span_2026("Divigel", 1007, "A1", weeks, mon)))
  expect_identical(jay_mon, span_2026("Divigel", 1008, "A1", weeks, mon))
})

test_that("the Jaydess rule overrides the IUD rule", {
  weeks <- weeks_between("2015-12-27", "2050-12-25")
  observed <- span_2026("Jaydess", 1, "E1", weeks)
  expect_identical(observed, span_2026("Divigel", 1008, "A1", weeks))
  expect_identical(observed, list(first = "2015-53", last = "2018-40", n = 145L))
  expect_false(identical(observed, span_2026("Divigel", 1680, "A1", weeks)))
  expect_false(identical(observed, span_2026("Divigel", 1009, "A1", weeks)))
})

test_that("PINNED: the minimum-dose loop overrides both the IUD and Jaydess rules", {
  # Precedence is decided by write order, and the minimum-dose loop writes
  # LAST, so it wins over both earlier rules rather than losing to them.
  #
  # `Mirena Primolut-Nor` uses only register spellings. The ladder never
  # strips the hyphen, so `produkt_clean` is `MirenaPrimolut-Nor` and the
  # `Mirena` rung fires: category E1, fddd := 1680. The minimum-dose loop then
  # matches the RAW product name against the `Primolut-Nor` workbook row
  # (4.66 mg/month, min 3 months): floor(1680/4.66) = 360 -> 360 * 28 = 10080.
  weeks <- weeks_between("2015-12-27", "2050-12-25")

  iud <- span_2026("Mirena Primolut-Nor", 1, "E1", weeks)
  expect_identical(iud, span_2026("Divigel", 10080, "A1", weeks))
  expect_identical(iud, list(first = "2015-53", last = "2043-32", n = 1441L))
  expect_false(identical(iud, span_2026("Divigel", 1680, "A1", weeks)))

  # `JaydessProvera` reaches the `Provera` rung (C4, above E1), takes the
  # Jaydess duration of 1008, and is then rewritten by the `Provera` row
  # (4 mg/month, min 3 months): floor(1008/4) = 252 -> 252 * 28 = 7056.
  jay <- span_2026("JaydessProvera", 1, "C4", weeks)
  expect_identical(jay, span_2026("Divigel", 7056, "A1", weeks))
  expect_identical(jay, list(first = "2015-53", last = "2035-17", n = 1009L))
  expect_false(identical(jay, span_2026("Divigel", 1008, "A1", weeks)))
})

# ------------------------------------------------------------ encoding trap ----

test_that("the ladder classifies a registered sign under every declared encoding", {
  # The raw batch declares Encoding() == "latin1"; a direct fread() gives
  # "unknown". The pinned case is the LAST one: latin1 bytes declared
  # "unknown", which is what production sees and what a test written against
  # "latin1" alone never exercises.
  utf8 <- "Livial®"
  latin1 <- iconv(utf8, "UTF-8", "latin1")
  Encoding(latin1) <- "latin1"
  unknown_utf8 <- utf8
  Encoding(unknown_utf8) <- "unknown"
  unknown_latin1 <- latin1
  Encoding(unknown_latin1) <- "unknown"

  expect_identical(Encoding(unknown_latin1), "unknown")
  expect_identical(charToRaw(unknown_latin1), charToRaw(latin1))

  for (nm in names(ladders)) {
    for (x in list(utf8, latin1, unknown_utf8, unknown_latin1)) {
      expect_identical(
        suppressWarnings(classify(ladders[[nm]], x)),
        "F1",
        info = paste(nm, Encoding(x))
      )
    }
  }
})

test_that("base gsub fails on the unknown-declared bytes the ladder survives", {
  # Witness for WHY the test above must use "unknown" and not "latin1": a
  # normaliser written with base gsub passes the latin1 case and errors on the
  # unknown one. Asserted on the error's EXISTENCE, never on its text.
  skip_if_not(
    grepl("UTF-8", Sys.getlocale("LC_CTYPE"), fixed = TRUE),
    "byte validity is locale-dependent; pinned only in a UTF-8 locale"
  )
  latin1 <- iconv("Livial®", "UTF-8", "latin1")
  Encoding(latin1) <- "latin1"
  unknown_latin1 <- latin1
  Encoding(unknown_latin1) <- "unknown"

  expect_identical(gsub(" ", "", latin1), latin1)
  expect_error(suppressWarnings(gsub(" ", "", unknown_latin1)))
  expect_identical(suppressWarnings(classify(ladders$v20250909, unknown_latin1)), "F1")
})

# ------------------------------------------------------ approach resolution ----

test_that("each category alone resolves to the pinned approach values", {
  prods <- workbook_products()
  weeks <- weeks_between("2015-01-05", "2016-03-28")
  cat_of <- classify(ladders$v20250909, prods)
  skeleton <- run_2026(
    data.table::data.table(
      lopnr = seq_along(prods),
      produkt = prods,
      edatum = as.Date("2015-02-02"),
      fddd = 365
    ),
    ids = seq_along(prods),
    weeks = weeks
  )
  key <- data.table::data.table(id = seq_along(prods), cat = cat_of)
  got <- skeleton[key, on = "id"][
    !is.na(cat),
    .(
      a1 = paste(sort(unique(approach1)), collapse = "|"),
      a3 = paste(sort(unique(approach3)), collapse = "|")
    ),
    keyby = .(cat)
  ]

  systemic <- c(
    "A1", "A2", "A6", "A7",
    "B1", "B11", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9"
  )
  expect_setequal(got[a1 != "local_or_none_mht"]$cat, systemic)
  expect_true(all(got[a1 != "local_or_none_mht"]$a1 == "local_or_none_mht|systemic_mht"))

  # every remaining classified category resolves to local_or_none_mht alone,
  # on all three approaches
  expect_setequal(
    got[a1 == "local_or_none_mht"]$cat,
    c("A3", "A4", "A5", "C1", "C3", "C4", "D2", "D3", "E1", "F1", "G1", "H1", "I2")
  )
  expect_true(all(got[a1 == "local_or_none_mht"]$a3 == "local_or_none_mht"))
})

test_that("PINNED DEFECT: F1, G1 and H1 are read by no approach rule", {
  # Adding one of these to an A1 person changes nothing anywhere, while every
  # progestogen category in the next test does change approach3. That is the
  # executable proof that these three are classified and then read by nothing.
  weeks <- weeks_between("2015-01-05", "2016-12-26")
  rep_product <- c(A1 = "Divigel", F1 = "Livial", G1 = "Duavive", H1 = "Nebido")
  expect_identical(
    classify(ladders$v20250909, unname(rep_product)),
    unname(names(rep_product))
  )

  alone <- run_2026(
    data.table::data.table(
      lopnr = 1L, produkt = "Divigel", edatum = as.Date("2015-02-02"), fddd = 365
    ),
    ids = 1L,
    weeks = weeks
  )
  approaches <- c("approach1", "approach2", "approach3")
  for (k in c("F1", "G1", "H1")) {
    with_k <- run_2026(
      data.table::data.table(
        lopnr = 1L,
        produkt = c("Divigel", unname(rep_product[k])),
        edatum = as.Date("2015-02-02"),
        fddd = 365
      ),
      ids = 1L,
      weeks = weeks
    )
    expect_identical(with_k[, ..approaches], alone[, ..approaches], info = k)
  }
})

test_that("the progestogen categories DO change approach3 when combined with A1", {
  weeks <- weeks_between("2015-01-05", "2016-12-26")
  rep_product <- c(
    C1 = "Crinone", C3 = "Cerazette", C4 = "Provera",
    D2 = "Nexplanon", D3 = "Jadelle", E1 = "Mirena", I2 = "Exlutena"
  )
  expect_identical(
    classify(ladders$v20250909, unname(rep_product)),
    unname(names(rep_product))
  )
  expected <- c(
    C1 = "estrogen_progesterone_bioidentical",
    C3 = "estrogen_progesterone_synthetic",
    C4 = "estrogen_progesterone_synthetic",
    D2 = "estrogen_progesterone_synthetic",
    D3 = "estrogen_progesterone_synthetic",
    E1 = "estrogen_progesterone_synthetic",
    I2 = "estrogen_progesterone_synthetic"
  )
  for (k in names(rep_product)) {
    skeleton <- run_2026(
      data.table::data.table(
        lopnr = 1L,
        produkt = c("Divigel", unname(rep_product[k])),
        edatum = as.Date("2015-02-02"),
        fddd = 365
      ),
      ids = 1L,
      weeks = weeks
    )
    expect_identical(
      sort(unique(skeleton$approach3)),
      sort(c(unname(expected[k]), "local_or_none_mht")),
      info = k
    )
  }
})

# ----------------------------------------------- downstream / the contract ----

test_that("PINNED: an entry point returns a logical flag, not the skeleton", {
  # Both entry points end with data.table::shouldPrint(skeleton), so the
  # returned value is a length-1 logical. Never assign the result.
  weeks <- weeks_between("2015-01-05", "2016-03-28")
  skeleton <- data.table::CJ(id = 1L, isoyearweek = weeks, sorted = TRUE)
  out <- add_lmed_v20250909(
    skeleton,
    data.table::data.table(
      lopnr = 1L, produkt = "Divigel", edatum = as.Date("2015-02-02"), fddd = 90
    ),
    verbose = FALSE
  )
  expect_type(out, "logical")
  expect_length(out, 1L)
  expect_false(data.table::is.data.table(out))

  skeleton23 <- data.table::CJ(id = 1L, isoyearweek = weeks, sorted = TRUE)
  out23 <- suppressMessages(add_lmed_v20230509(
    skeleton23,
    data.table::data.table(
      p1163_lopnr_personnr = 1L, produkt = "Divigel",
      edatum = as.Date("2015-02-02"), fddd = 90
    )
  ))
  expect_type(out23, "logical")
  expect_length(out23, 1L)
})

test_that("PINNED: the entry point reorders the caller's skeleton by reference", {
  # `setorder()` runs on the caller's own object, so "only adds columns" is
  # false: the row order changes too.
  weeks <- weeks_between("2015-01-05", "2016-03-28")
  skeleton <- data.table::CJ(id = 1:3, isoyearweek = weeks, sorted = TRUE)
  data.table::setorder(skeleton, -id, -isoyearweek)
  before <- data.table::copy(skeleton[, .(id, isoyearweek)])

  suppressWarnings(add_lmed_v20250909(
    skeleton,
    data.table::data.table(
      lopnr = 1L, produkt = "Divigel", edatum = as.Date("2015-02-02"), fddd = 90
    ),
    verbose = FALSE
  ))
  after <- skeleton[, .(id, isoyearweek)]

  expect_false(identical(before, after))
  expect_identical(after, before[order(id, isoyearweek)])
  expect_identical(after$id[1], 1L)
})

test_that("PINNED: the entry point deletes caller columns that collide with internals", {
  # The approach loop creates and then deletes its working columns. A caller
  # column of the same name is destroyed, so "only adds columns" is false in a
  # second way.
  weeks <- weeks_between("2015-01-05", "2016-03-28")
  skeleton <- data.table::CJ(id = 1L, isoyearweek = weeks, sorted = TRUE)
  skeleton[, systemic_mht := TRUE]
  skeleton[, local_or_none_mht := TRUE]
  skeleton[, row_min := 42]
  skeleton[, run_systemic_mht := 7]
  skeleton[, keepme := 1L]

  suppressWarnings(add_lmed_v20250909(
    skeleton,
    data.table::data.table(
      lopnr = 1L, produkt = "Divigel", edatum = as.Date("2015-02-02"), fddd = 90
    ),
    verbose = FALSE
  ))

  for (gone in c("systemic_mht", "local_or_none_mht", "row_min", "run_systemic_mht")) {
    expect_false(gone %in% names(skeleton), info = gone)
  }
  expect_true("keepme" %in% names(skeleton))
  expect_identical(unique(skeleton$keepme), 1L)
})

test_that("PINNED: the 2023 entry point leaves a key on the caller's skeleton", {
  weeks <- weeks_between("2015-01-05", "2016-03-28")
  skeleton <- data.table::data.table(
    id = 1L,
    isoyearweek = weeks
  )
  expect_null(data.table::key(skeleton))
  suppressMessages(suppressWarnings(add_lmed_v20230509(
    skeleton,
    data.table::data.table(
      p1163_lopnr_personnr = 1L, produkt = "Divigel",
      edatum = as.Date("2015-02-02"), fddd = 90
    )
  )))
  expect_identical(data.table::key(skeleton), c("id", "isoyearweek"))
})
