#' Synthetic LMED prescriptions in the 2023 column layout
#'
#' A small synthetic dispensed-prescription table shaped like the Swedish
#' prescribed drug register (LMED) extract that [add_lmed_v20230509()] consumes.
#' It carries no real person data.
#'
#' @format A [data.table::data.table] with 128 rows and 4 columns:
#' \describe{
#'   \item{p1163_lopnr_personnr}{integer. Person identifier, matched against the
#'     skeleton's `id` column. 18 distinct persons, numbered 1 to 18.}
#'   \item{produkt}{character. Dispensed product name, as printed in the
#'     register, e.g. `"Divigel"`, `"Vagifem"`, `"Nexplanon"`.}
#'   \item{edatum}{`Date`. Date the prescription was dispensed.}
#'   \item{fddd}{numeric. Dispensed duration in days. One row is deliberately
#'     negative, to exercise the invalid-interval path.}
#' }
#'
#' @source Synthetic. Generated by `dev/generate_fake_lmed.R` with
#'   `set.seed(42)`, and identical to [fake_lmed_2026] except that the person
#'   identifier is named `p1163_lopnr_personnr` rather than `lopnr`. Together
#'   with [fake_skeleton_mht] it deliberately spans 312 ISO weeks (2015-W02 to
#'   2020-W52, six ISO years), so that the 156-week minimum-duration rule is
#'   reachable: one person's treatment episode runs longer than 156 weeks and
#'   another's runs shorter. The fixture also contains prescription gaps both
#'   at or below four weeks (bridged) and above four weeks (not bridged),
#'   one person with clashing concurrent prescriptions, at least one product
#'   per reachable product category, and one product name absent from the
#'   category ladder.
#'
#' @seealso [fake_lmed_2026], [fake_skeleton_mht]
#' @keywords datasets
"fake_lmed_2023"

#' Synthetic LMED prescriptions in the 2026 column layout
#'
#' A small synthetic dispensed-prescription table shaped like the Swedish
#' prescribed drug register (LMED) extract that [add_lmed_v20250909()] consumes.
#' It carries no real person data.
#'
#' @format A [data.table::data.table] with 128 rows and 4 columns:
#' \describe{
#'   \item{lopnr}{integer. Person identifier, matched against the skeleton's
#'     `id` column. 18 distinct persons, numbered 1 to 18.}
#'   \item{produkt}{character. Dispensed product name, as printed in the
#'     register, e.g. `"Divigel"`, `"Vagifem"`, `"Nexplanon"`.}
#'   \item{edatum}{`Date`. Date the prescription was dispensed.}
#'   \item{fddd}{numeric. Dispensed duration in days. One row is deliberately
#'     negative, so that [add_lmed_v20250909()] drops it with a warning.}
#' }
#'
#' @source Synthetic. Generated by `dev/generate_fake_lmed.R` with
#'   `set.seed(42)`. Together with [fake_skeleton_mht] it deliberately spans
#'   312 ISO weeks (2015-W02 to 2020-W52, six ISO years), so that the 156-week
#'   minimum-duration rule is reachable: one person's treatment episode runs
#'   longer than 156 weeks and another's runs shorter. The fixture also
#'   contains prescription gaps both at or below four weeks (bridged) and above
#'   four weeks (not bridged), one person with clashing concurrent
#'   prescriptions, at least one product per reachable product category, and
#'   one product name absent from the category ladder.
#'
#' @seealso [fake_lmed_2023], [fake_skeleton_mht]
#' @keywords datasets
"fake_lmed_2026"

#' Synthetic person-week skeleton
#'
#' The person-week grid that [add_lmed_v20230509()] and [add_lmed_v20250909()] write
#' their exposure columns into. One row per person per ISO week, with no
#' payload columns: the entry points add every derived column themselves.
#'
#' @format A [data.table::data.table] with 5616 rows (18 persons x 312 ISO
#'   weeks) and 2 columns:
#' \describe{
#'   \item{id}{integer. Person identifier, 1 to 18, matching the identifier
#'     column of [fake_lmed_2023] and [fake_lmed_2026].}
#'   \item{isoyearweek}{character. ISO year and week as `"YYYY-WW"`, from
#'     `"2015-02"` to `"2020-52"`, sorting correctly as a string.}
#' }
#'
#' @source Synthetic. Generated by `dev/generate_fake_lmed.R` with
#'   `set.seed(42)`, from the same weekly grid as [fake_lmed_2023] and
#'   [fake_lmed_2026]. The grid deliberately spans 312 ISO weeks (2015-W02 to
#'   2020-W52, six ISO years) so that the 156-week minimum-duration rule is
#'   reachable within the fixture.
#'
#' @seealso [fake_lmed_2023], [fake_lmed_2026]
#' @keywords datasets
"fake_skeleton_mht"
