on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

name: Check and pkgdown

jobs:
  r-package:
    permissions:
      contents: write
    uses: papadopoulos-lab/pptemplate/.github/workflows/r-package.yml@cc27a7b9c43958e223c717669da67eec32f8a84c
