on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

name: Check and pkgdown

jobs:
  r-package:
    permissions:
      contents: write
    uses: papadopoulos-lab/pptemplate/.github/workflows/r-package.yml@568e122a8adef696dcf4ea05f2ee652ddc6775f3
