on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

name: Check and pkgdown

jobs:
  r-package:
    permissions:
      contents: write
    uses: papadopoulos-lab/pptemplate/.github/workflows/r-package.yml@0ec90b6e4686500bb242acbf4f9c560d814d88af
